import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { TerminalCard, dominantFaction } from '@/components/cards/TerminalCard';
import fixture from '@/fixtures/tessera.json';
import type { Pet } from '@/lib/pet/schema';

const tessera = fixture as Pet;

describe('TerminalCard', () => {
  it('renders pet name in uppercase', () => {
    render(<TerminalCard pet={tessera} />);
    expect(screen.getByText('TESSERA')).toBeInTheDocument();
  });

  it('renders title', () => {
    render(<TerminalCard pet={tessera} />);
    expect(screen.getByText('尽调炼狱的执灯人')).toBeInTheDocument();
  });

  it('renders all 4 skill names', () => {
    render(<TerminalCard pet={tessera} />);
    for (const s of tessera.skills) {
      expect(screen.getByText(new RegExp(s.name))).toBeInTheDocument();
    }
  });

  it('renders all 6 stat names with numeric values', () => {
    const { container } = render(<TerminalCard pet={tessera} />);
    for (const k of ['HP', 'ATK', 'DEF', 'SPD', 'INT', 'LUK']) {
      expect(screen.getByText(k)).toBeInTheDocument();
    }
    // 88 / 82 / 94 等 stat 数字也应该出现
    expect(container.textContent).toContain('88');
    expect(container.textContent).toContain('96');
  });

  it('renders 3 faction labels', () => {
    render(<TerminalCard pet={tessera} />);
    expect(screen.getByText('CHAT')).toBeInTheDocument();
    expect(screen.getByText('COWORK')).toBeInTheDocument();
    expect(screen.getByText('CODE')).toBeInTheDocument();
  });

  it('renders brand watermark petarena.xyz (not "Generated by Claude")', () => {
    const { container } = render(<TerminalCard pet={tessera} />);
    expect(container.textContent).toContain('petarena.xyz');
    expect(container.textContent).not.toContain('Generated by Claude');
    expect(container.textContent).not.toContain('GENERATED BY CLAUDE');
  });

  it('does NOT render generation_evidence (privacy red line)', () => {
    const withEv = {
      ...tessera,
      generation_evidence: ['SUPER_SECRET_EVIDENCE_STRING_42'],
    };
    const { container } = render(<TerminalCard pet={withEv} />);
    expect(container.textContent).not.toContain('SUPER_SECRET_EVIDENCE_STRING_42');
    expect(container.textContent).not.toMatch(/evidence/i);
  });

  it('applies longName class when name exceeds 10 chars', () => {
    const longName = { ...tessera, name: 'VeryLongPetName' };
    const { container } = render(<TerminalCard pet={longName} />);
    const nameEl = container.querySelector('[class*="petName"]');
    expect(nameEl?.className).toMatch(/longName/);
  });

  it('falls back to chat as dominant on three-way tie', () => {
    expect(dominantFaction({ chat: 50, cowork: 50, code: 50 })).toBe('chat');
  });

  it('picks the highest faction otherwise', () => {
    expect(dominantFaction({ chat: 30, cowork: 90, code: 60 })).toBe('cowork');
    expect(dominantFaction({ chat: 30, cowork: 60, code: 90 })).toBe('code');
  });
});
